### ISSUE TITLE
No subjective data is recorded

### ISSUE THREAD

**Issue by ping-zhao** [khaivngo/QuickEval#71] opened 2015-03-06 09:58 UTC
I continuously finished experiment in rank order mode with four observers. When I was checking the results in the report, I found out that no subjective data is recorded in the final report for group 2 to 7, but not group 1. So now I have no choice but temporarily rolled back to an old version first and continue the experiment because more observers are coming.

Branch: development
Version: 931d2cdac6532f642b1942b2866bb6cf01e536ed

**Comment by khaivngo** [comment] 2015-03-07 14:35
Not sure what is wrong on your end, everything posts correctly for rank order experiments. Are you running a clean version without caching?

**Comment by mariuspedersen** [comment] 2015-03-07 20:06
I was able to reproduce this error. The first image in the set is recorded, but not the second. So you will need to add two image sets to the same experiment to reproduce it.

**Comment by khaivngo** [comment] 2015-03-28 21:08
Is this the same as issue #34?

**Comment by mariuspedersen** [comment] 2015-03-28 21:12
No, I do not think so. In this issue the results for image set 2 (and later) is not recorded. Issue #34 it seems to be "opposite", that the results for image set 1 is not shown/recorded while the others are.

**Comment by khaivngo** [comment] 2015-03-28 21:16
Ping refers to that the "results for group 1 were missing" in #34 and it seems like this is same issue as he states that the picture sets 2-7 are recorded but not for picture set 1?

**Comment by mariuspedersen** [comment] 2015-03-28 21:19
In the attached image in #34 it is listed imageset2-10, and not imageset 1. So results for imageset 1 is missing there. 

I have been able to recreate this issue (#71), and I know that this is an issue. I have not been able to recreate #34

**Comment by khaivngo** [comment] 2015-03-28 21:21
Okey, I think this is the sentence that confuses me: " I found out that no subjective data is recorded in the final report for group 2 to 7, but not group 1".

**Comment by mariuspedersen** [comment] 2015-03-28 21:22
That confused me too, but I looked at the images. I would focus on this issue, since I have been able to recreate it. It seems like the results for the second and later image sets is not stored in the database.

**Comment by mariuspedersen** [comment] 2015-05-06 08:56
To follow up on this, there is a group of people in France who have used QuickEval and the rank order with multiple imagesets. Only results for the first imageset has been stored (I also checked in the database, andI can only find the first imageset). It seems like the results for the rest of the imagesets are not stored.

**Comment by mariuspedersen** [comment] 2015-05-21 07:16
@khaivngo Could this be the next issue that you prioritize? Thanks.

**Comment by khaivngo** [comment] 2015-05-21 17:29
@mariuspedersen Have looked at it and fixed it and tested that it saves each picture. Could you verify it?

**Closed** 2015-05-21 17:31 UTC
Labels: bug, in progress, P1
